### ISSUE TITLE
@unicode/unicode-14.0.0 1.2.1 is on npmjs.com -- this repo seems to build 1.2.0

### ISSUE THREAD

**Issue by SnarkBoojum** [node-unicode/node-unicode-data#67]
I'm still having issues with building @unicode/unicode-14.0.0 from here ; I'm using the latest commit 243f19e8, and I don't get the same JS module at the end:
- mine says it's 1.2.0 (based on a three-months old commit), while npmjs has 1.2.1 (one month old) ;
-  it has various changes here and there ;
- most notably, I lack all Emoji_* and Extended_Pictographic in Binary_Property ;
- but I have a few more things in Block (Chorasmian, ..., Tangut_Supplement).

I feel like I'm back with the question of issue #51...

**Comment by JLHwung** [comment]
This issue has been fixed in https://github.com/node-unicode/node-unicode-data/pull/72
