### ISSUE TITLE
Support Unicode 15 + Emoji 15

### ISSUE THREAD

**Issue by mathiasbynens** [node-unicode/node-unicode-data#69]

**Comment by mathiasbynens** [comment]
The beta data files are already available. Here are the commits that add support for it: https://github.com/node-unicode/node-unicode-data/compare/0f5bfbcc6f2dac90c17d2c84241d822d83812711%5E...71cb96b6d6eacc867ac2f702a4dc0eb5d1df5b47 I’ll keep this issue open until the official Unicode 15 + Emoji 15 release happens, since the data might still change before then.

**Comment by JLHwung** [comment]
This issue can be closed now that Unicode 15 has been released.
