### ISSUE TITLE
CJK Unified Ideographs Extension I block is not covered in `15.1.0-scripts.txt`

### ISSUE THREAD

**Issue by JLHwung** [node-unicode/node-unicode-data#71]
The CJK Unified Ideographs Extension I block `2EBF0..2EE5D` is sorta last-minute changes included in the Unicode 15.1 (c.f. [L2/23-114R](https://www.unicode.org/L2/L2023/23114r-unc-extension-i.pdf)). It was not included in the draft fetched as of March 2023. 

There might be other changes that are not in my radar, I suggest we fetch the UCD again and update the data.

**Comment by mathiasbynens** [comment]
I’ve updated to the latest draft data now.

Some category/block names are now getting recognized as “undefined”: https://github.com/node-unicode/unicode-15.1.0/commit/f7936fca50ce6bf9ccce1e189ed0658380910a03 Perhaps there is a bug in the data file format, or we have to update our parser. I’ll keep this issue open until this is fixed.

**Comment by mathiasbynens** [comment]
I’ve updated to the latest draft data now.

Some `Block` and `Line_Break` names are now getting recognized as “undefined”: https://github.com/node-unicode/unicode-15.1.0/commit/f7936fca50ce6bf9ccce1e189ed0658380910a03 Either there is a bug in the data file format, or if it’s an intentional change, we have to update our parser. I’ll keep this issue open until this is fixed.

**Comment by JLHwung** [comment]
https://github.com/node-unicode/unicode-15.1.0/blob/f7936fca50ce6bf9ccce1e189ed0658380910a03/Block/undefined/regex.js#L1

U+0870 is from Arabic Extended-B introduced in Unicode 14, which happens to be not included in https://github.com/mathiasbynens/unicode-loose-match/blob/master/data/mappings.js. Since `unicode-loose-match` is built on Unicode 11, I suggest we update the data for `unicode-loose-match` and see if the new blocks introduced after Unicode 11 can be recognized.

**Comment by mathiasbynens** [comment]
I just published `unicode-loose-match@2.6.0` containing those changes.

**Comment by JLHwung** [comment]
I can confirm that `Blocks/undefined` is gone after `unicode-loose-match` is bumped to 2.6.0. We may want to publish the updated packages `unicode-12.0.0` .. `unicode-15.0.0` as well, since they all benefit from the `unicode-loose-match` update.

**Comment by mathiasbynens** [comment]
I believe this has been resolved. Please comment & reopen if I missed anything!

**Comment by JLHwung** [comment]
Umm, it seems that the `unicode-loose-match` is not actually bumped because I don't observe any changes from `unicode-15.1.0@1.4.2` to `unicode-15.1.0@1.5.0`: https://github.com/node-unicode/unicode-15.1.0/compare/v1.4.2..v1.5.0

It should be fixed in #72.

**Comment by JLHwung** [comment]
@mathiasbynens Can you cut the new release?

**Comment by mathiasbynens** [comment]
Done! See the v1.5.2 releases.

**Comment by JLHwung** [comment]
Thanks. I am wondering why https://github.com/node-unicode/unicode-15.1.0/blob/main/Block/undefined/regex.js is not removed, maybe we should clean up the `output` folder before publish? Anyway it is not emergent and we can fix that in the next regular update.
